### ISSUE TITLE
UPerf support Multus

### ISSUE THREAD

**Issue by jtaleric** [cloud-bulldozer/ripsaw#219]
If Multus is available we should configure the pods to use Multus...

**Comment by jeniferh** [comment]
Some thoughts...
Multus allows you to add additional interfaces by calling other network plugins, so we need both multus and the desired plugin available.

The CNI config CR needs to be created before hand. Depending on which network plugin you want to test, it may also require something to be configured on the node(s).
   CNI config CR ex. for macvlan plugin: https://docs.openshift.com/container-platform/4.1/networking/managing-multinetworking.html#creating-a-cni-configuration-for-an-additional-interface-as-a-cr

Then ripsaw will need to add an annotation to the pods using the net name created by the CR. Uperf will need to use the correct IP since the pod will have eth0 (pod net ip), eth1 (plugin1 ip), etc.

**Comment by jtaleric** [comment]
> Some thoughts...
> Multus allows you to add additional interfaces by calling other network plugins, so we need both multus and the desired plugin available.
> 
> The CNI config CR needs to be created before hand. Depending on which network plugin you want to test, it may also require something to be configured on the node(s).
> CNI config CR ex. for macvlan plugin: https://docs.openshift.com/container-platform/4.1/networking/managing-multinetworking.html#creating-a-cni-configuration-for-an-additional-interface-as-a-c

Right. The user would be required to setup Multus with whatever plugin they want to test.

> 
> Then ripsaw will need to add an annotation to the pods using the net name created by the CR. Uperf will need to use the correct IP since the pod will have eth0 (pod net ip), eth1 (plugin1 ip), etc.

Right, we would possibly need to add logic to get the IP address, as right now Rispaw will capture the pod IP not the plugin IP.

**Comment by jeniferh** [comment]
Also should note, we need this multus bug fixed: https://bugzilla.redhat.com/show_bug.cgi?id=1732598
(there is a workaround in comment4 for testing)

**Comment by aakarshg** [comment]
can we close this out @jtaleric ? given we've the multus stuff added to uperf?
