### ISSUE TITLE
RFE: Cerberus checks between iterations of same benchmark

### ISSUE THREAD

**Issue by aakarshg** [cloud-bulldozer/ripsaw#327]
This is a followup to #323, to utilize the cerberus integration between the iterations of a benchmark run. So ideally for uperf this would be a check to the cerberus endpoint somewhere at https://github.com/cloud-bulldozer/ripsaw/blob/master/roles/uperf-bench/templates/workload.yml.j2#L88

**Comment by dry923** [comment]
@aakarshg I started working on this. Some interesting issues I've come across so far. An example from the fio client template inside it's for loop

```
{% if cerberus_url is defined and cerberus_url != "" %}
             if [ `curl -s {{cerberus_url}}` ]; then echo \"Cerberus reporting failure. Exiting\"; exit 1; fi;
{% endif %}
```

This works and stops the pod in its tracks. However, this doesn't necessarily stop the pod from getting restarted. In some tests I ended up with this:

```
NAME                                    READY   STATUS    RESTARTS   AGE
benchmark-operator-f5f897789-5dw5c      3/3     Running   0          4m38s
fio-client-673072a7-27hbs               0/1     Error     0          3m34s
fio-client-673072a7-7b2bg               0/1     Error     0          2m44s
fio-client-673072a7-89wfr               0/1     Error     0          3m38s
fio-client-673072a7-tqlrt               0/1     Error     0          84s
fio-client-673072a7-wfh8j               0/1     Error     0          3m24s
fio-server-1-benchmark-673072a7-pkwr7   1/1     Running   0          4m3s
fio-server-2-benchmark-673072a7-p9tfp   1/1     Running   0          4m2s
```

Additionally, since my test simply involved killing the etcd pod (which restarts rather quickly), there were times when the Cerberus check was done and the etcd pod was back up so Cerberus reported  good health even if the container was failing because of the bad report.

The same thing could easily happen within the for loop of the fio client.

One thought is do we want workload pods to restart when failed or not? This might be a workload-to-workload question. If restarting was disabled then it simply would have been done after it caught the first error.

Thoughts?
