### ISSUE TITLE
Be opinionated about our namespace

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#54]
We are facing a few issues related to namespaces and contexts. Ultimately, it makes sense for all resources created by the benchmark operator to exist in a single namespace. It seems that other operator projects are explicit about this -- defining the namespace directly in their deployment and config files.

We have begun hard-coding the 'benchmark' namespace in deploy files, but not for the operator.yaml file (so currently the operator itself will deploy to $current_context), and we rely on {{ meta.namespace }} across the roles.

It seems sub-optimal to scatter-shot the hard-coding of the 'benchmark' namespace across the many files where this context needs to be set. What other options do we have?

**Comment by jtaleric** [comment]
So, the gist of this would be we hard-code everything to `namespace: benchmark`? 

Is the complication introduced when we try to have an Operator install and orchestrate and Operator?

**Comment by aakarshg** [comment]
So currently, when we do operator install, we deploy it to the namespace set in current-context so if the user did oc project benchmark before deploying operator then it'll be deployed to benchmark namespace otherwise whatever was in current context. The issue furthers with the deployments/rbacs applied by operator itself such as in the case of couchbase where we use {{ meta.namespace }}. So if the user did oc project or changed namespace to benchmark it'd work fine otherwise cause issues.

Either way, when we are creating resources for the operator or through the operator, I propose that they all be defaulted to benchmark namespace as that's pushed by through the docs and best practices instead of relying on what current-context holds.

**Comment by aakarshg** [comment]
After the conversation with @dustinblack , we've come to conclusion that we should be defaulting to `ripsaw` namespace for the roles/rolebindings and such. For the roles we should read from a variable that can be set at higher level through group_vars hopefully. This would be done through #50

**Comment by dustinblack** [comment]
+1 -- The `ripsaw` namespace should be less likely to collide with something that a user has existing than the `benchmark` namespace. It's unfortunate that we have to hard-code this in multiple places in the deploy/ and resources/ files, but we don't see a way around that. A global var for the roles should be doable, though.
