### ISSUE TITLE
Collect and display more detail for CI

### ISSUE THREAD

**Issue by aakarshg** [cloud-bulldozer/ripsaw#71]
- [x] - CI should move on running workloads even if one fails
- [x] - CI should display workloads that passed and the ones that failed
- [ ] - Collect logs of a particular run through tmp/ansible-operator/runner/benchmark.example.com/v1alpha1/Benchmark/ripsaw/example-benchmark/artifacts/latest/stdout file in pod
- [ ] - Upload these logs somewhere so user can access them later

**Comment by aakarshg** [comment]
@dry923 @jtaleric @dustinblack after we run CI on 4.2 through dev-scripts

**Comment by dry923** [comment]
Given many of the ci failures seem to be during wait for functions we could re-create a wait function that dumps a pods log file when a timeout occurs. Since we are using pipefail in the test scripts I do not think we can do a simple check against the return code. We instead could do something like:

Current command from test_ycsb.sh:
kubectl wait --for=condition=Complete jobs -l 'name=ycsb-load' -n my-ripsaw --timeout=300s

New command:
wait_for("kubectl wait --for=condition=Complete jobs -l 'name=ycsb-load' -n my-ripsaw ", 300, $ycsb_load_pod)

In wait_for we do a simple loop and upon hitting the timeout we can dump debug information.

**Comment by jtaleric** [comment]
> Given many of the ci failures seem to be during wait for functions we could re-create a wait function that dumps a pods log file when a timeout occurs. Since we are using pipefail in the test scripts I do not think we can do a simple check against the return code. We instead could do something like:
> 
> Current command from test_ycsb.sh:
> kubectl wait --for=condition=Complete jobs -l 'name=ycsb-load' -n my-ripsaw --timeout=300s
> 
> New command:
> wait_for("kubectl wait --for=condition=Complete jobs -l 'name=ycsb-load' -n my-ripsaw ", 300, $ycsb_load_pod)
> 
> In wait_for we do a simple loop and upon hitting the timeout we can dump debug information.

*THIS* 

Capturing more detailed debug code will help us triage _what_ went wrong.

**Comment by bengland2** [comment]
in minishift this command fails:
```
++ kubectl -n my-ripsaw logs --tail=40 -l name=benchmark-operator -c benchmark-operator
```
I prefer:
```
    bopod=$(kubectl get pods | grep benchmark-operator | awk '{ print $1 }')
    kubectl logs $bopod -c benchmark-operator
```
which does work in minishift and should work in the other ones too, right?

**Comment by aakarshg** [comment]
@dry923 @jtaleric thoughts on this

**Comment by bengland2** [comment]
minishift is dead.   So I think our lowest common denominator became KNI and this shouldn't be an issue anymore?

**Comment by aakarshg** [comment]
I think the issue was more around collecting logs and other information to help us find the problem with pr, which i think we've some or most of it in place but i'm not sure if it's enough to close this out altogether?
