### ISSUE TITLE
CI wait_clean function doesn't actually do anything

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#97]
In the CI `test.sh` script, we call the `cleanup_resources` function followed by the `wait_clean` function.

```
...
source tests/common.sh

trap cleanup_resources EXIT

wait_clean
...
```

The `wait_clean` function checks 30 times effectively for the operator pod to not be running.

```
function wait_clean {
  for i in {1..30}; do
    if [ `kubectl get pods --namespace ripsaw | grep bench | wc -l` -ge 1 ]; then
      sleep 5
    else
      break
    fi
  done
}
```

However, the `cleanup_resources` function does not include commands to stop the operator pod.

```
function cleanup_resources {
  echo "Exiting after cleanup of resources"
  kubectl delete -f resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
  kubectl delete -f deploy
  marketplace_cleanup
}
```

This results in the `wait_clean` function simply running through its 30 iterations, doing nothing.

I'm not entirely sure of the intention, so I don't want to propose a solution, but I will point out that the `cleanup_operator_resources` function is defined and _does_ include the commands to delete the operator pod, but this function is not actually used anywhere.

```
function cleanup_operator_resources {
  delete_operator
  cleanup_resources
  wait_clean
}
```

**Comment by aakarshg** [comment]
`wait_clean` function doesn't just check for the operator pod to not be running, but it effectively waits for any pods that are still in terminating state. This is to provide a buffer time for all pods to safely terminate, before the next build begins on same executor, this is also why we start with a `wait_clean` when we start[1]. 

It's all to ensure that when we're checking for number of pods through check_pods we're actually getting the right count from just this build. 

About `cleanup_operator_resources` function, it was defined to be made use of when running a full e2e tests without restarting operator pod, and it's used in the `full_test.sh` [2].

I hope that this clears up and gives an idea of why things were done in the above manner, it might not be the perfect way, but it was just to get the job done.

Since it's not necessarily a bug, I'm removing the label bug. Leaving the issue open for you to close when you feel that it's been resolved.

[1] https://github.com/cloud-bulldozer/ripsaw/blob/master/test.sh#L8
[2] https://github.com/cloud-bulldozer/ripsaw/blob/master/full_test.sh#L6

**Comment by dustinblack** [comment]
Still looks like a bug to me.

In this `if` statement from `wait_clean`:
```
if [ `kubectl get pods --namespace ripsaw | grep bench | wc -l` -ge 1 ]; then
```

The `-ge 1` will always evaluate to true if the operator pod is running. If we expect the operator pod to _not_ be running at this point, then we should be calling commands to stop it prior to running this `if` loop.

If we expect that the operator pod _may_ be running, and it is OK for it to be running, then the function should be extended to check for that so that it can pass instead of waiting 30 retries.

I'm also curious why after we wait for 30 retries, we will simply pass and move forward instead of failing out.

**Comment by dustinblack** [comment]
> We're not expecting that any pod may be running.

Then it seems to make sense to replace `cleanup_resources` with `cleanup_operator_resources` in the `test.sh` script so that we are explicitly deleting the operator pod before continuing.

**Comment by aakarshg** [comment]
That would cause issues as well, because operator pod is being deleted in the individual test already. So if it were to be deleted again, it'd throw an error. Thats the reason why we use `cleanup_resources` instead of `cleanup_operator_resources`

**Comment by aakarshg** [comment]
Closing this issue, as `wait_clean()` is not being used anymore following the merge of #120
